### ISSUE TITLE
Panic originating in `SeqBuf::remove`; annotated as "shouldn't panic"

### ISSUE THREAD

**Issue by cdata** [aecsocket/aeronet#19]
Hey there! I'm implementing `aeronet` / WebTransport in my game project.

I was having some fun testing out the nascent multiplayer implementation with a friend on a remote network and everything was going well. Then, suddenly, the server died.

I reviewed the server logs and saw this:

![image](https://github.com/user-attachments/assets/ed9619c7-cde4-497e-b4ac-24311f561dea)

Curious, I dug into the code and found the related implementation:

https://github.com/aecsocket/aeronet/blob/ab0a0f5efb6c5597425c0beaebea56f818bc6a09/crates/aeronet_transport/src/seq_buf.rs#L251-L289

The code is annotated with a claim that it should not panic:

```rs
#[expect(clippy::missing_panics_doc, reason = "shouldn't panic")]
```

**Comment by aecsocket** [comment]
This indeed is a bug (writing data structures is hard)! https://github.com/aecsocket/aeronet/pull/20 should fix this. With a fuzz test as well, so hopefully I can catch edge cases like this if they pop up again.
